id = "autohotkey"
name = "AutoHotkey"
version = "2.0.2"
schema_version = 1
authors = ["Alfredo Menezes"]
description = "AutoHotkey v1 language support for Zed with debugging"
repository = "https://github.com/CandyTek/tree-sitter-autohotkey"

[grammars.autohotkey]
repository = "file:///I:/Github/tree-sitter-autohotkey"
rev = "c2b04fb2a504d1336b70ca89c82f11156da0c059"
path = "."

[language_servers.autohotkey-lsp]
name = "AutoHotkey Language Server"
languages = ["AutoHotkey"]

[debug_adapters.autohotkey]
schema_path = "debug_adapter_schemas/autohotkey.json"
